language: cpp
compiler: gcc
addons:
    apt:
        sources:
            - kalakris-cmake
            - boost-latest
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:   
            - cmake
            - cmake-data
            - libboost-all-dev
            - protobuf-compiler 
            - libprotobuf-dev
            - zlib1g-dev
before_script:
  - cd core
  - mkdir build
  - cd build
  - cmake ..

script: make