sudo: false
language: 
    cpp
    csharp
os: linux
mono:
 - latest
compiler: gcc
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
    apt:
        sources:
            - kalakris-cmake
            - george-edison55-precise-backports # cmake 3.x
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - cmake
            - cmake-data
            - zlib1g-dev
            - libprotobuf-dev
            - protobuf-compiler
            - libboost1.55-all-dev
            - gcc-4.9
            - g++-4.9
            - mono-complete
            - nunit-console
before_script:
    - cd core
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
script:
    - make
    - cd test
    - ctest -V
    - cd ../../unity
    - mozroots --import --sync
    - mono --runtime=v4.0.30319 .nuget/NuGet.exe restore unity.Tests.sln
    - xbuild /p:Configuration=Debug /p:DefineConstants="CONSOLE" unity.Tests.sln
    - nunit-console UtymapLib.Tests/bin/Debug/UtymapLib.Tests.exe
