language: cpp
compiler: gcc
addons:
    apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'kalakris-cmake']
      packages: ['clang-3.7', 'cmake']
before_script:
  - cd core
  - mkdir build
  - cd build
  - cmake ..

script: make