sudo: false
language: cpp
os: linux
dist: precise
mono:
 - latest
compiler:
    - gcc
#    - clang
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
#    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
addons:
    apt:
        sources:
            - kalakris-cmake
            - george-edison55-precise-backports # cmake 3.x
            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
            - boost-latest
        packages:
            - cmake
            - cmake-data
            - zlib1g-dev
            - libprotobuf-dev
            - protobuf-compiler
            - libboost1.55-all-dev
            - gcc-4.9
            - g++-4.9
#            - clang-3.7
            - mono-complete
            - nunit-console
before_script:
    - cd core
    - mkdir build
    - cd build
script:
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - cd test
    - ctest -V
    - cd ../../../unity
    - mozroots --import --sync
    - mono --runtime=v4.0.30319 .nuget/NuGet.exe restore unity.Tests.sln
    - xbuild /p:Configuration=Debug /p:DefineConstants="CONSOLE" unity.Tests.sln
    - cp ../core/build/shared/libUtyMapLib.so UtymapLib.Tests/bin/Debug/
    - nunit-console -noshadow UtymapLib.Tests/bin/Debug/UtymapLib.Tests.exe
